apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: subscription-authorizer
  namespace: auth
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: subscription-authorizer
